# Generated by Django 5.2.16 on 2026-07-15 02:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arboles', '0003_alter_ubicacion_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=15, verbose_name='Estatus')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('nueva_especie_nombre', models.CharField(blank=True, default='', max_length=100, verbose_name='Nueva especie — nombre común')),
                ('nueva_especie_nombre_cientifico', models.CharField(blank=True, default='', max_length=150, verbose_name='Nueva especie — nombre científico')),
                ('nueva_especie_nativa', models.BooleanField(blank=True, null=True, verbose_name='Nueva especie — ¿es nativa?')),
                ('nueva_etiqueta', models.CharField(blank=True, default='', help_text='Código de la placa metálica si es un árbol nuevo.', max_length=50, verbose_name='Nueva etiqueta del árbol')),
                ('n1', models.FloatField(verbose_name='Nivel 1 (Hawksworth)')),
                ('n2', models.FloatField(verbose_name='Nivel 2 (Hawksworth)')),
                ('n3', models.FloatField(verbose_name='Nivel 3 (Hawksworth)')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('imagen1', models.CharField(blank=True, default='', max_length=500, verbose_name='Imagen 1')),
                ('imagen2', models.CharField(blank=True, default='', max_length=500, verbose_name='Imagen 2')),
                ('imagen3', models.CharField(blank=True, default='', max_length=500, verbose_name='Imagen 3')),
                ('imagen4', models.CharField(blank=True, default='', max_length=500, verbose_name='Imagen 4')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('motivo_rechazo', models.TextField(blank=True, default='', verbose_name='Motivo de rechazo')),
                ('arbol_existente', models.ForeignKey(blank=True, help_text='Seleccionar si el árbol ya está registrado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='arboles.arbol', verbose_name='Árbol existente')),
                ('especie_existente', models.ForeignKey(blank=True, help_text='Seleccionar si la especie ya está registrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='arboles.especie', verbose_name='Especie existente')),
                ('id_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='arboles.ubicacion', verbose_name='Ubicación del nuevo árbol')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
