# Generated by Django 5.2.16 on 2026-07-15 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='n1',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.5)], verbose_name='Nivel 1 (Hawksworth)'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='n2',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.5)], verbose_name='Nivel 2 (Hawksworth)'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='n3',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.5)], verbose_name='Nivel 3 (Hawksworth)'),
        ),
    ]
