# Generated by Django 5.2.16 on 2026-07-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitud_n1_alter_solicitud_n2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='coordenadas_exactas',
            field=models.CharField(blank=True, default='', help_text='Punto exacto del árbol en formato lat,long o x,y.', max_length=500, verbose_name='Coordenadas exactas del árbol'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nueva_etiqueta',
            field=models.CharField(blank=True, default='', help_text='Código alfanumérico del árbol si es un árbol nuevo.', max_length=50, verbose_name='Nueva etiqueta del árbol'),
        ),
    ]
