# Generated by Django 5.2.16 on 2026-07-14 18:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kilos', models.FloatField(help_text='Masa exacta en kg registrada en la báscula institucional.', verbose_name='Kilos')),
                ('fecha', models.DateField(help_text='Fecha del registro físico y validación del pesaje.', verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Recolección',
                'verbose_name_plural': 'Recolecciones',
                'db_table': 'recolecciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
