# Generated by Django 5.2.16 on 2026-07-14 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recoleccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recoleccion',
            name='responsable',
            field=models.ForeignKey(help_text='Estudiante que realizó la recolección.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recolecciones', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
