# Generated by Django 5.2.16 on 2026-07-14 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cuatrimestre',
            field=models.IntegerField(default=1, help_text='Período lectivo actual del alumno (1 al 11).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo',
            field=models.CharField(default='N/A', help_text='Grupo escolar del cuatrimestre vigente.', max_length=20, verbose_name='Grupo'),
        ),
    ]
