# Generated by Django 5.2.16 on 2026-07-14 18:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arboles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('n1', models.FloatField(help_text='Medición Hawksworth — componente 1.', verbose_name='Nivel 1 (Hawksworth)')),
                ('n2', models.FloatField(help_text='Medición Hawksworth — componente 2.', verbose_name='Nivel 2 (Hawksworth)')),
                ('n3', models.FloatField(help_text='Medición Hawksworth — componente 3.', verbose_name='Nivel 3 (Hawksworth)')),
                ('status_reporte', models.CharField(choices=[('Validado', 'Validado'), ('Rechazado', 'Rechazado')], max_length=15, verbose_name='Estatus del reporte')),
                ('hora', models.DateTimeField(help_text='Timestamp exacto de transmisión del reporte desde el dispositivo.', verbose_name='Hora del reporte')),
                ('observaciones', models.TextField(blank=True, help_text='Notas complementarias sobre el estado físico del espécimen.', null=True, verbose_name='Observaciones')),
                ('id_arbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='arboles.arbol', verbose_name='Árbol')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
                'ordering': ['-hora'],
            },
        ),
    ]
