# Generated by Django 5.2.16 on 2026-07-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Notas complementarias sobre el estado físico del espécimen.', verbose_name='Observaciones'),
        ),
    ]
