# Generated by Django 5.2.16 on 2026-07-15 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='n1',
            field=models.FloatField(help_text='Medición Hawksworth — componente 1. Rango válido: 0.0 a 2.5.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.5)], verbose_name='Nivel 1 (Hawksworth)'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='n2',
            field=models.FloatField(help_text='Medición Hawksworth — componente 2. Rango válido: 0.0 a 2.5.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.5)], verbose_name='Nivel 2 (Hawksworth)'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='n3',
            field=models.FloatField(help_text='Medición Hawksworth — componente 3. Rango válido: 0.0 a 2.5.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.5)], verbose_name='Nivel 3 (Hawksworth)'),
        ),
    ]
