# Generated by Django 5.2.16 on 2026-07-14 18:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre común u ordinario por el cual la comunidad identifica la planta.', max_length=100, verbose_name='Nombre común')),
                ('nombre_cientifico', models.CharField(help_text='Nomenclatura binominal científica formal.', max_length=150, unique=True, verbose_name='Nombre científico')),
                ('nativa', models.BooleanField(default=False, help_text='True si la especie es originaria de la región, False si es introducida.', verbose_name='¿Es nativa?')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'db_table': 'especies',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordenadas', models.CharField(help_text='Estructura de datos compuesta con la información geoespacial del área.', max_length=500, unique=True, verbose_name='Coordenadas')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(help_text='Código alfanumérico de la placa metálica fijada al tronco.', max_length=50, verbose_name='Etiqueta')),
                ('nivel_infestacion', models.FloatField(default=0.0, help_text='Porcentaje ponderado promedio de infestación global del último censo.', verbose_name='Nivel de infestación')),
                ('estado', models.CharField(choices=[('Sano', 'Sano'), ('Infestado', 'Infestado'), ('Limpieza', 'Limpieza'), ('Saneado', 'Saneado')], default='Sano', max_length=15, verbose_name='Estado')),
                ('fecha_reporte', models.DateField(help_text='Fecha de la última modificación del estatus fitosanitario.', verbose_name='Fecha de último reporte')),
                ('imagen1', models.CharField(blank=True, default='', help_text='Ruta relativa URL de la imagen 1.', max_length=500, verbose_name='Imagen 1')),
                ('imagen2', models.CharField(blank=True, default='', help_text='Ruta relativa URL de la imagen 2.', max_length=500, verbose_name='Imagen 2')),
                ('imagen3', models.CharField(blank=True, default='', help_text='Ruta relativa URL de la imagen 3.', max_length=500, verbose_name='Imagen 3')),
                ('imagen4', models.CharField(blank=True, default='', help_text='Ruta relativa URL de la imagen 4.', max_length=500, verbose_name='Imagen 4')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arboles', to='arboles.especie', verbose_name='Especie')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arboles', to='arboles.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Árbol',
                'verbose_name_plural': 'Árboles',
                'db_table': 'arboles',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
