# Generated by Django 5.2.16 on 2026-07-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arboles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre amigable para identificar la ubicación dentro del campus.', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='nivel_infestacion',
            field=models.FloatField(default=0.0, help_text='Suma de los tres niveles Hawksworth del último censo. Rango válido: 0.0 a 7.5.', verbose_name='Nivel de infestación'),
        ),
    ]
