# Generated by Django 5.2.16 on 2026-07-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arboles', '0002_ubicacion_nombre_alter_arbol_nivel_infestacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(help_text='Nombre amigable para identificar la ubicación dentro del campus.', max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
