# Generated by Django 5.2.16 on 2026-07-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arboles', '0003_alter_ubicacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='coordenadas',
            field=models.CharField(blank=True, default='', help_text='Punto exacto del árbol en formato lat,long o x,y.', max_length=500, verbose_name='Coordenadas exactas'),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='etiqueta',
            field=models.CharField(help_text='Código alfanumérico del árbol.', max_length=50, verbose_name='Etiqueta'),
        ),
    ]
